--- 
- 
  gather_facts: false
  hosts: all
  name: "Windows Update"
  tasks: 
    - 
      name: "Running Windows Update"
      win_updates: 
        category_names: 
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
          - DefinitionUpdates
        reboot: true
