version: '3.3'

services:
 web1:
   image: nginx
   volumes:
     - ./web1/nginx.conf:/etc/nginx/nginx.conf
     - ./web1/html:/usr/share/nginx/html

 web2:
   image: nginx
   volumes:
     - ./web2/nginx.conf:/etc/nginx/nginx.conf
     - ./web2/html:/usr/share/nginx/html
 
 elb01:
   image: haproxy
   volumes:
     - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
   ports:
     - "80:80"
     - "88:88"
