---
- hosts: win
  gather_facts: no
  tasks:

  - win_firewall_rule:
      name: Zabbix
      localport: 10052
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes
  
  - win_chocolatey:
      name: zabbix-agent
      state: present
 
  - win_service:
      name: 'Zabbix Agent'
      state: stopped

  - win_file:
      path: C:\ProgramData\zabbix\zabbix_agentd.conf
      state: absent

  - win_copy:
      src: /root/ansible/books/win01/zabbix_agentd.conf
      dest: 'C:\ProgramData\zabbix\zabbix_agentd.conf'
      remote_src: no

  - win_service:
      name: 'Zabbix Agent'
      state: started
